### ISSUE TITLE
firefoxで削除処理が動作しない

### ISSUE THREAD

**Issue by itotoru** [EC-CUBE/product-priority-plugin#4]
お世話になります。

どちらにコメントしてよいものかよくわからず、こちらへ書きました。
突然のコメントで誠に失礼いたします。

当方、管理画面で商品マスタの表示並び替えのプラグインを探しており、
こちらへたどり着き、これはと思いダウンロードおよび開発環境への
インストールをしてみました。（2016/12/30）

商品の登録と並び替えの反映はきちんと行われておりますが、
おすすめ順の登録をした後、チェックボックスにチェックを入れて
削除ボタンを押して、ポップアップを「はい」で実行してみたのですが
削除が行われませんでした。

その後確認しましたところ、
ProductPriority\Resource\template\admin\index.twigの以下箇所（188行目）

`                $.ajax({
                    url: '{{ url("admin_product_priority_delete", { categoryId : categoryId }) }}',
                    type: 'POST',
                    data: productIds,
                }).done(function (data) {
                    console.log(data);
                }).fail(function () {
                    console.log('fail');
                });
`

で失敗しているようです。（firebugのコンソールでfailとなっておりました。）

当方の開発環境（xampp）は以下の通りです。
EC-CUBE　3.0.13
サーバーOS　Windows NT 6.2 build 9200 (Windows 8 Professional Edition) i586
DBサーバー　MySQL 10.1.13-MariaDB
WEBサーバー　Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23
PHP　5.6.23
HTTPユーザーエージェント　Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101
Firefox/50.0

大変恐縮ですが、何かアドバイスを頂ければ幸いです。
どうぞよろしくお願いいたします。

**Comment by itotoru** [comment]
自レスで大変恐縮です。

その後、動作を確認してみましたところ、以下の通りでした。

　Firefox：動かない
　Chrome：動く

ブラウザ毎で動作が違っているようでしたので、それを基に
ネットで検索してみましたところ、

http://nplll.com/archives/2016/05/jquerypost.php
http://qiita.com/kazuki1213/items/75b29ecec9c236866871

上記の内容を見つけましたので、プラグインの
ProductPriority\Resource\template\admin\index.twigの以下箇所（188行目）
に`async: false`を追加してみました。

`                $.ajax({
                    url: '{{ url("admin_product_priority_delete", { categoryId : categoryId }) }}',
                    type: 'POST',
                    data: productIds,
                    async: false,
                }).done(function (data) {
                    console.log(data);
                }).fail(function () {
                    console.log('fail');
                });
`

これで動作させてみたところ、firefoxでも
削除が行われるようになりました。

もしこの内容でも問題ないようであれば
反映頂ければと思っております。

どうもお騒がせいたしまして失礼いたしました。

**Comment by chihiro-adachi** [comment]
@itotoru
不具合のご報告ありがとうございます。現象確認いたしました。
修正についても、ご提示いただいた内容で問題ありませんので、反映させていただければと思います。
よろしくお願いいたします。

**Comment by itotoru** [comment]
@chihiro-adachi 
年明け早々で大変恐縮です。
ご確認、ご回答頂きましてありがとうございました。

どうぞよろしくお願いいたします。<(_ _)>

**Comment by chihiro-adachi** [comment]
refs #5
